### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [jimmc414/1filellm#2]
Hi @sammcj and @jimmc414 

that's a fantastic tool, thanks for sharing! I was just wondering under which conditions one could reuse the code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by jimmc414** [comment]
Great advice and I'm thrilled you find it useful.  I have added a
permissive MIT license linked here:
https://github.com/jimmc414/1filellm/blob/main/LICENSE

Thank you!
Jim

**Comment by haesleinhuepf** [comment]
awesome, thanks for the quick response!
