### ISSUE TITLE
Thank you for your contribution!

### ISSUE THREAD

**Issue by limaolin2017** [jimmc414/1filellm#6]
when I run this command : python test_onefilellm.py

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/player/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "/Users/player/Downloads/1filellm-main/test_onefilellm.py", line 5, in <module>
    from onefilellm import process_github_repo, process_arxiv_pdf, process_local_folder, fetch_youtube_transcript, crawl_and_extract_text
  File "/Users/player/Downloads/1filellm-main/onefilellm.py", line 30, in <module>
    raise EnvironmentError("GITHUB_TOKEN environment variable not set.")
OSError: GITHUB_TOKEN environment variable not set.

**Comment by jimmc414** [comment]
Hi.  You need to create a github personal token and save it to your environment.  The instructions are located here:

https://github.com/jimmc414/1filellm?tab=readme-ov-file#obtaining-a-github-personal-access-token

Good luck!
