### ISSUE TITLE
Incorrect tiktoken Version Specified in `requirements.txt`

### ISSUE THREAD

**Issue by aliciusschroeder** [jimmc414/1filellm#7]
While reviewing the `requirements.txt`, I noticed that the specified version of `tiktoken` (0.0.3) does not exist. This could lead to issues when installing dependencies. I've tested the functionality with `tiktoken` version 0.6.0, and everything seems to work flawlessly. I suggest updating the version in `requirements.txt` accordingly to avoid future installation problems.

**Comment by jimmc414** [comment]
fixed in PR #8 and merged here:  https://github.com/jimmc414/1filellm/commit/7009f2408db5d872f2e69509d0561807d7653bc5

Thanks for taking the time!
